name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: yarn install, lint, build
        run: |
          yarn install
          yarn lint
          yarn generate:prod
      - name: run Lighthouse CI
        run: |
          sudo yarn global add @lhci/cli@0.4.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
